# Site settings

baseurl = "http://replace-this-with-your-hugo-site.com/"
theme = "ridingbytes"
title = "Riding Bytes"
languageCode = "en-us"
copyright = "Copyright (c) 2015, RIDING BYTES; all rights reserved."


[permalinks]
    blog = "/:year/:month/:day/:slug/"


[params]

    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "Ramon Bartl"
    description = "Riding Bytes UG (haftungsbeschränkt)"
    keywords = "Python,Plone,Zope,JavaScript,CoffeeScript,Web,Development,Consulting"
    dateformat = "Mon, Jan 2, 2006"


    # navigation
    [params.navigation]
        title = "Navigation"
        description = ""

        [[params.navigation.list]]
            title = "Home"
            href = "/"
            submenu = [
                ["/#services", "Services"],
                ["/#team", "Team"],
                ["/#customers", "Customers"]
            ]
        [[params.navigation.list]]
            title = "Blog"
            href = "/blog"
        [[params.navigation.list]]
            title = "Services"
            href = "/services"
            submenu = [
                ["/services/#development", "Development"],
                ["/services/#uiux", "UI/UX"],
                ["/services/#consulting", "Consulting"],
                ["/services/#administration", "Administration"]
            ]
        [[params.navigation.list]]
            title = "Contact"
            href = "/contact"


    # main site sections
    [params.sections]

        # home section /
        [params.sections.home]
            title = "Home"
            href = "/"

        # blog section /blog
        [params.sections.blog]
            title = "Blog"
            subtitle = ""

        # services section /services
        [params.sections.services]
            title = "Services"
            subtitle = ""

        # blog section /contact
        [params.sections.contact]
            title = "Contact"
            subtitle = "Contact us today for any more details"

        # 404 section /404
        [params.sections.fourohfour]
            title = "404"
            subtitle = "Sorry, the Page your requested could not be found"
            description = "Page Not Found"


    # slider
    [params.slider]

        # slide 1
        [[params.slider.slides]]
            img = "header1.jpg"
            alt = "Computer Background"
            [[params.slider.slides.layers]]
                img = "rb_logo_weiss.png"
                alt = "Riding Bytes"
                start = "750"
                y = "210"
            [[params.slider.slides.layers]]
                description = "International Coding Company"
                start = "800"
                y = "400"
                cls = "font-accident-one-bold fontcolor-invert"
            [[params.slider.slides.layers]]
                link = "Tell me more"
                href = "#services"
                start = "950"
                y = "480"
                cls = "page-scroll btn btn-lg btn-wh-str"


    # services
    [params.services]
        title = "Services"
        description = "The Internet is our Riding Stable"
        [[params.services.list]]
            title = "Web Development"
            description = ""
            cls = "icon-box"
            href = "/services/#development"
            details = [
                ["Programming"],
                ["Databases"],
                ["APIs"]
            ]
        [[params.services.list]]
            title = "UI / UX Design"
            description = ""
            cls = "icon-layers"
            href = "/services/#uiux"
            details = [
                ["Web based UIs"],
                ["Responsive"],
                ["Mobile/Desktop"]
            ]
        [[params.services.list]]
            title = "Consulting"
            description = ""
            cls = "icon-eye"
            href = "/services/#consulting"
            details = [
                ["Analysis"],
                ["Advice"],
                ["Support"]
            ]
        [[params.services.list]]
            title = "Administration"
            description = ""
            cls = "icon-server"
            href = "/services/#administration"
            details = [
                ["Installation"],
                ["Maintenance"],
                ["Monitoring"]
            ]


    # team
    [params.team]
        title = "Our amazing team"
        description = "Potential is not a matter of size"
        [[params.team.members]]
            img = "ramon.jpg"
            name = "Ramon Bartl"
            position = "Owner & Coder"
            social = [
                ["fa-twitter", "https://twitter.com/ramonbartl"],
                ["fa-linkedin", "https://www.linkedin.com/in/ramonski"],
                ["fa-github", "https://github.com/ramonski"],
                ["fa-facebook", "https://www.facebook.com/ramonbartl"]
            ]
        [[params.team.members]]
            img = "lucky.jpg"
            name = "Lucky Luke"
            position = "Byte Riding Horse"
            social = [
                ["fa-twitter", "https://twitter.com/ridingbytes"],
                ["fa-linkedin", "https://www.linkedin.com/company/riding-bytes"],
                ["fa-github", "https://github.com/ridingbytes"],
                ["fa-facebook", "https://www.facebook.com/ridingbytes"]
            ]


    # customers
    [params.customers]
        title = "Customers"
        description = "Worldwide Clients"
        [[params.customers.list]]
            name = "2degrees Mobile Limited"
            logo = "2degrees.jpg"
            href = "http://www.2degreesmobile.co.nz"
            description = ""
        [[params.customers.list]]
            name = "nexiles GmbH"
            logo = "nexiles.png"
            href = "http://www.nexiles.com"
        [[params.customers.list]]
            name = "Gletscher Cola"
            logo = "gletschercola.jpg"
            href = "http://www.gletschercola.de"


    # systems
    [params.systems]
        [[params.systems.links]]
            title = "Plone"
            url = "https://plone.org"
            img = "plone.png"
        [[params.systems.links]]
            title = "ExtJS"
            url = "https://sencha.com"
            img = "extjs.png"
        [[params.systems.links]]
            title = "Odoo"
            url = "https://odoo.com"
            img = "odoo.png"
        [[params.systems.links]]
            title = "GitHub"
            url = "https://github.com"
            img = "github.png"
        [[params.systems.links]]
            title = "Python"
            url = "https://python.com"
            img = "python.png"
        [[params.systems.links]]
            title = "CoffeeScript"
            url = "http://coffescript.org"
            img = "coffeescript.png"


    # about the company
    [params.about]
        title = "Riding Bytes"
        [[params.about.infos]]
            text = "RIDING BYTES is a web development company, which is specialized in UI/UX design, server based solutions and consulting services."
        [[params.about.infos]]
            text = "With over 10 years of experience in web development and consulting, we provide the right solutions for small, medium and large enterprises."


    # contact information
    [params.contact]
        title = "Contact"
        name = "Riding Bytes"
        #phone = "+49 160 5551008"
        email = "hello@ridingbytes.com"
        address = "RIDING BYTES UG (haftungsbeschränkt), Einöde 49A, 87474 Buchenberg, Germany"
        web = "http://ridingbytes.com"

        [params.contact.form]
            title = "Contact us"
            subtitle  = "Ready to start your next project with us? That's great! Send us an email and we will get back to you as soon as possible!"
            buttonText = "Send message"
            to = "info@ridingbytes.com"

        # 'warning' defines error messages for invalid inputs
        [params.contact.form.name]
            text = "Your Name *"
            warning = "Please enter your name."
        [params.contact.form.email]
            text = "Your Email *"
            warning = "Please enter your email address."
        [params.contact.form.phone]
            text = "Your Phone *"
            warning = "Please enter your phone number."
        [params.contact.form.message]
            text = "Your Message *"
            warning = "Please enter a message."


    # social media links
    [params.follow]
        title = "Follow us"
        [[params.follow.list]]
            title = "Facebook"
            href = "https://www.facebook.com/ridingbytes"
            cls = "fa fa-facebook"
        [[params.follow.list]]
            title = "GitHub"
            href = "https://github.com/ridingbytes"
            cls = "fa fa-github"
        [[params.follow.list]]
            title = "LinkedIn"
            href = "https://www.linkedin.com/company/riding-bytes"
            cls = "fa fa-linkedin"
        [[params.follow.list]]
            title = "Twitter"
            href = "https://twitter.com/ridingbytes"
            cls = "fa fa-twitter"


    # flickr feed
    [params.flickr]
        title = "Flickr Feed"


    # copyright
    [params.copyright]
        year = "2015"
        text = "All rights reserved"

        # additional copyright links
        #[[params.copyright.links]]
            #title = "Terms & Conditions"
            #url = ""
        [[params.copyright.links]]
            title = "Legal Notice"
            url = "/about/imprint"
